local cfg = {}

cfg.items = {
	["m-armacaotec"] = { "M-Munição de TEC",0.20 },
	["m-armacaoak"] = { "M-Munição de AK",0.20 },
	["m-armacaomp5"] = { "M-Munição de MP5",0.20 },
	["m-armacaog3"] = { " M-Munição de G3",0.20 },
	["materialmunicao"] = { "Material De Munição",0.20 },
	["distintivopolicial"] = { "distintivopolicial",0 },
	["uvas"] = { "Uvas",0.5 },
	["cobre"] = { "Cobre",0.2 },
	["plastico"] = { "Plastico",0.2 },
	["borrachar"] = { "Borracha",0.2 },
	["pano"] = { "Pano",0.2 },
	["linha"] = { "Linha",0.2 },
	["vidro"] = { "Vidro",0.2 },
	["fioeletronico"] = { "Fio Eletronico",0.3 },
	["bateria"] = { "Bateria",0.2 },
	["celular"] = { "Celular",1.0 },
	["roupas"] = { "Roupas",3.0 },
	["gps"] = { "Gps",0.2 },
	["alianca"] = { "Aliança",0 },
	["bandagem"] = { "Bandagem",0.7 },
	["cerveja"] = { "Cerveja",0.7 },
	["tequila"] = { "Tequila",0.7 },
	["vodka"] = { "Vodka",0.7 },
	["whisky"] = { "Whisky",0.7 },
	["conhaque"] = { "Conhaque",0.7 },
	["absinto"] = { "Absinto",0.7 },
	["dinheirosujo"] = { "Dinheiro Sujo",0 },
	["repairkit"] = { "Kit de Reparos",1 },
	["algemas"] = { "Algemas",1 },
	["cordas"] = { "Cordas",1 },
	["capuz"] = { "Capuz",0.5 },
	["lockpick"] = { "Lockpick",10 },
	["masterpick"] = { "Masterpick",10 },
	["militec"] = { "Militec-1",0.8 },
	["compattach"] = { "Modificador de Armas",0.80 },
	["energetico"] = { "Energético",0.3 },
	["mochila"] = { "Mochila",0 },
	["adubo"] = { "Adubo",0.30 },
	["fertilizante"] = { "Fertilizante",0.30 },
	["maconha"] = { "Maconha",0.3 },
	["etiqueta"] = { "Etiqueta",0 },
	["pendrive"] = { "Pendrive",0.1 },
	["relogioroubado"] = { "Relógio Roubado",0.3 },
	["pulseiraroubada"] = { "Pulseira Roubada",0.2 },
	["anelroubado"] = { "Anel Roubado",0.2 },
	["colarroubado"] = { "Colar Roubado",0.2 },
	["brincoroubado"] = { "Brinco Roubado",0.2 },
	["carteiraroubada"] = { "Carteira Roubada",0.2 },
	["tabletroubado"] = { "Tablet Roubado",0.2 },
	["sapatosroubado"] = { "Sapatos Roubado",0.2 },
	["folhadecoca"] = { "Folha de Cocaina",0.30 },
	["pastadecoca"] = { "Pasta de Cocaina",0.30 },
	["cocaina"] = { "Cocaína",0.3 },
	["fungo"] = { "Fungo",0.8 },
    ["dietilamina"] = { "Dietilamina",0.8 },
    ["lsd"] = { "LSD",0.3 },
	["acidobateria"] = { "Ácido de bateria",0.30 },
	["anfetamina"] = { "Anfetamina",0.30 },
	["metanfetamina"] = { "Metanfetamina",0.3 },
	["lancaperfume"] = { "Lança Perfume",0.3 },
	["pecadearma"] = { "Peça de Arma",0.20 },
	["armacaodearma"] = { "Armacao de Arma",0.20 },
	["armacaodeak"] = { "Armacao de Ak",0.20 },
	["armacaodeg3"] = { "Armacao de G3",0.20 },
	["armacaodemp5"] = { "Armacao de Mp5",0.20 },
	["armacaodetec"] = { "Armacao de Tec",0.20 },
	["pecadearma"] = { "Peça de arma",0.8 },
	["logsinvasao"] = { "Logs de Invasão",0.1 },
	["keysinvasao"] = { "Keys para Invasão",1.0 },
	["radio"] = { "Radio",1.0 },
	["tecido"] = { "Tecido",0.8 },
    ["couro"] = { "Couro",0.8 },
    ["algodao"] = { "Algodao",0.8 },
    ["latas"] = { "Latas",0.8 },
    ["cafeina"] = { "Cafeina",0.0 },
    ["taurina"] = { "Taurina",0.0 },
	["serra"] = { "Serra",5.0 },
	["furadeira"] = { "Furadeira",5.0 },
	["c4"] = { "C-4",5.0 },
	["keycard"] = { "Keycard",0.1 },
	["laranja"] = { "Laranja",0.8 },
	["telefonedescartavel"] = { "Telefone Descartável",0.6 },
	["placa"] = { "Placa",1.0 },
	["aneldecompromisso"] = { "Anel de Compromisso",1.0 },
	["colardeperolas"] = { "Colar de Pérolas",1.0 },
	["pulseiradeouro"] = { "Pulseira de Ouro",1.0 },
	["chocolate"] = { "Chocolate",1.0 },
	["pirulito"] = { "Pirulito",1.0 },
	["buque"] = { "Buquê de Flores",1.0 },
	["placametal"] = { "Placa de Metal",0.03 },
	["metal"] = { "Metal",0.03 },
	["capsulas"] = { "Capsulas",0.05 },
	["polvora"] = { "Polvora",0.06 },
	["detergenteneutro"] = { "Detergente Neutro",0.2 },
	["bicarbonatodesodio"] = { "Bicarbonato de Sódio",0.2 },
	["agua"] = { "Água",0.2 },
	["vinagre"] = { "Vinagre",0.2 },
	["alvejantecaseiro"] = { "Alvejante Caseiro",1.5 },
	["alvejantepremium"] = { "Alvejante Premium",1.5 },
}

local function load_item_pack(name)
	local items = module("cfg/item/"..name)
	if items then
		for k,v in pairs(items) do
			cfg.items[k] = v
		end
	end
end

load_item_pack("armamentos")

return cfg